### PR TITLE
add card editor unit tests

### PR DESCRIPTION
**Pull request by grezisek1**

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Test Case Review Based on Requirements

#### Requirement 1: Test if clicking on `<Card />` enters edit mode
The test case "entered edit mode after click" checks if a form element is present after clicking on the card, which is a reasonable proxy for the card being in edit mode. This satisfies the first requirement.

```javascript
it("entered edit mode after click", () => {
  fireEvent.click(card);
  formRef = card.querySelector("form");
  expect(formRef).not.toBeFalsy();
});
```

#### Requirement 2: Test if clicking outside edit mode exits edit mode
The test case "left edit mode after click outside" attempts to verify that clicking outside the card exits edit mode by checking if the card contains the base element of the render result. However, this logic is flawed. The correct approach would be to check if the form element is no longer present after clicking outside.

```javascript
it("left edit mode after click outside", () => {
  fireEvent.click(cardRenderResult.baseElement);
  formRef = card.querySelector("form");
  expect(formRef).toBeFalsy();
});
```

#### Requirement 3: Test if `onUpdateCard` is being fired when exiting edit mode
The test case "fired onUpdateCard leaving edit mode" checks if `onUpdateCard` has been called once. However, this test is not isolated properly; it depends on the previous test cases. Each test should be independent. The test should simulate exiting edit mode and then check if `onUpdateCard` was called.

```javascript
it("fired onUpdateCard leaving edit mode", () => {
  // Simulate exiting edit mode
  fireEvent.click(cardRenderResult.baseElement);
  expect(mockUpdateCard).toHaveBeenCalledTimes(1);
});
```

#### Requirement 4: Test if value on textarea is being set when firing change event in edit mode
The test case "fired onUpdateCard after close" is misleadingly named and does not match the requirement. It should be testing if the value of a textarea changes, not if `onUpdateCard` fires. The logic within the test correctly simulates a change event on the textarea and checks the value, but the test name and description need to be updated.

```javascript
it("textarea value is set on change event in edit mode", () => {
  // Assuming formRef and textarea are properly defined and selected
  const value = "123";
  fireEvent.change(textarea, { target: { value } });
  expect(textarea.value).toBe(value);
});
```

### Summary of Issues and Suggestions

1. **Incorrect Test Isolation**: Tests are not isolated; they depend on the state changes from previous tests. Each test should set up its own conditions and not rely on side effects from others.
2. **Misleading Test Description**: The description for the test that checks the textarea value change does not match the requirement. It should be renamed to accurately reflect what it's testing.
3. **Incorrect Logic for Exiting Edit Mode**: The logic used to determine if edit mode has been exited is incorrect. It should check for the absence of the form element after simulating a click outside the card.

### Suggested Changes

- Isolate tests properly by setting up and tearing down conditions within each test.
- Rename the test for checking textarea value change to match its purpose.
- Correct the logic for testing if clicking outside exits edit mode by checking for the absence of the form element.

```javascript
// Corrected example for exiting edit mode and checking onUpdateCard call
it("exits edit mode and fires onUpdateCard when clicking outside", () => {
  // Setup: Enter edit mode
  fireEvent.click(card);
  
  // Action: Click outside to exit edit mode
  fireEvent.click(document.body); // Assuming clicking body simulates clicking outside
  
  // Assert: Edit mode exited and onUpdateCard called once
  const formRef = card.querySelector("form");
  expect(formRef).toBeFalsy();
  expect(mockUpdateCard).toHaveBeenCalledTimes(1);
});
```

### Conclusion
The code changes partially cover the task requirements but have issues with test isolation, misleading descriptions, and incorrect logic for exiting edit mode. The suggested changes should address these issues to ensure that each requirement is properly tested.

**Comment by grezisek1** [comment]
> Requirement 2: Test if clicking outside edit mode exits edit mode
> The test case "left edit mode after click outside" attempts to verify that clicking outside the card exits edit mode by checking _if the card contains the base element of the render result_. 

That is not true. That check is only to ensure, that im clicking outside of the card. Look at `expect(formRef).toBeFalsy();` three lines below to see the test.

> this test is not isolated properly; it depends on the previous test cases. The test should simulate exiting edit mode and then check if onUpdateCard was called.

To exit the edit mode, i need to be in edit mode first, so I must ensure it is open. I sure can duplicate the opening code just to remove the checks within, but that is for nothing if the opening is broken.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Review Summary:
The provided code changes in `src/components/Card/Card.test.tsx` aim to cover the unit tests for the `<Card />` component as per the task requirements. The tests are structured to check for edit mode entry, edit mode exit, firing of the `onUpdateCard` callback, and textarea value change within the edit mode.

### Code Review Based on Requirements:

1. **Test if clicking on `<Card />` enters edit mode**
   - The test "entered edit mode after click" checks if a form element is present after clicking on the card, which implies that the card has entered edit mode. This satisfies the first requirement.

2. **Test if clicking outside edit mode exits edit mode**
   - The test "left edit mode after click outside" attempts to verify that clicking outside the card exits edit mode by checking if the card contains the base element of the render result, which is not a correct approach. The test should check for the absence of form elements or specific edit mode indicators to confirm that edit mode has been exited. This test does not correctly satisfy the second requirement.

3. **Test if `onUpdateCard` is being fired when exiting edit mode**
   - The test "fired onUpdateCard leaving edit mode" checks if `mockUpdateCard` has been called once. However, this test is flawed because it does not simulate the action that would trigger exiting edit mode (such as clicking outside or submitting the form). It only checks if the function was called at some point during the test suite execution. This does not satisfy the third requirement as it does not confirm the specific action that should trigger the callback.

4. **Test if value on textarea is being set when firing change event in edit mode**
   - The test "changed input value" correctly simulates a change event on what is assumed to be a textarea and checks if the value has been updated. This satisfies the fourth requirement, assuming that `formRef.elements[0]` is indeed a textarea.

### Suggestions for Improvement:

- For requirement 2, ensure that you simulate a click outside of the card and then check for a specific condition that indicates that edit mode has been exited, such as:
  ```javascript
  // Assuming that 'editMode' class is added to card when it's in edit mode
  fireEvent.click(document.body); // Simulate click outside
  expect(card.classList.contains('editMode')).toBeFalsy();
  ```

- For requirement 3, you need to simulate the action that triggers exiting edit mode before checking if `onUpdateCard` was called:
  ```javascript
  fireEvent.click(document.body); // Simulate click outside to exit edit mode
  expect(mockUpdateCard).toHaveBeenCalledTimes(1);
  ```

- Additionally, it would be beneficial to reset mocks before each test to ensure independence of test cases:
  ```javascript
  beforeEach(() => {
    mockUpdateCard.mockReset();
  });
  ```

- The current tests are dependent on each other due to shared state (`formRef`). Tests should be independent, and any setup required for each test should be done within that test or in a `beforeEach` block.

### Conclusion:
The code changes partially cover the task requirements. The tests for entering edit mode and changing textarea value are correctly implemented, but the tests for exiting edit mode and verifying the `onUpdateCard` callback need to be revised to accurately reflect user interactions and isolate test cases.

**Comment by grezisek1** [comment]
> The test should check for the absence of form elements

It does exactly that.

>  it does not simulate the action that would trigger exiting edit mode. It only checks if the function was called at some point during the test suite execution.

During "left edit mode after click outside", to be exact. Yes, it does not simulate the action itself, since it should check the result and not make a new result.

**Review by NerdbordMentor — APPROVED** [review]
Force approved. Hope you're not cheating!

**Pull request merged**
